version: '3.8'
services:
  back:
    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - "5000:80"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #   depends_on:
  #     - elasticsearch
  #     - logstash
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #     - ElasticsearchUrl=http://elasticsearch:9200
  #     - LogstashHost=logstash
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
  #   environment:
  #     - "discovery.type=single-node"
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - "9200:9200"
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.6.2
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.15.2
  #   volumes:
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline
  #     - ./logstash/config:/usr/share/logstash/config
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ports:
  #     - "9600:9600"
  #     - "5044:5044"
  #   depends_on:
  #     - elasticsearch
